version: '2'
services:
  nginx:
    volumes:
      - "./nginx/dev.conf:/etc/nginx/conf.d/default.conf"

  node:
    ports:
     - "8080:8080"

  front:
    ports:
     - "3000:3000"

  db:
    ports:
      - "5432:5432"
