version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - "./nginx/dev.conf:/etc/nginx/conf.d/default.conf"
      - "./front:/home/front"

  node:
    ports:
     - "8080:8080"
    environment:
      - NODE_ENV=development

  front:
    ports:
     - "3000:3000"
    environment:
      - NODE_ENV=development

  db:
    ports:
      - "5432:5432"
