version: '2'
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - "./nginx:/etc/nginx/conf.d"
    - "./front:/home/front"

  node:
    restart: always
    build:
      context: .
      dockerfile: dockerfile_back
    volumes:
     - "./back:/home/back"
    networks:
      actualisation_network:
        ipv4_address: 172.0.0.100
    depends_on:
      - "db"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  front:
    restart: always
    build:
      context: .
      dockerfile: dockerfile_front
    volumes:
     - "./front:/home/front"
    networks:
      actualisation_network:
        ipv4_address: 172.0.0.110

  db:
    image: postgres
    restart: always
    networks:
      actualisation_network:
        ipv4_address: 172.0.0.150
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

networks:
  actualisation_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/16
          gateway: 172.0.0.1

volumes:
 postgres-data:
