version: '2'
services:
  node:
    volumes:
      - '/mnt/datalakepe/:/mnt/datalakepe/'
    environment:
      - NODE_ENV=production

  front:
    environment:
      - NODE_ENV=production

  front-admin:
    environment:
      - NODE_ENV=production
