version: '2'
services:
  node:
    ports:
     - "8080:8080"
    environment:
      - DATABASE_URL=postgres://actu-user:actu-pass@172.0.0.150:5432/actualisation
  
  front:
    ports:
     - "3000:3000"
  
  db:
    environment:
      - POSTGRES_DB=actualisation
      - POSTGRES_USER=actu-user
      - POSTGRES_PASSWORD=actu-pass
    ports:
      - "5432:5432"
